### ISSUE TITLE
A very little abstraction layer in S3

### ISSUE THREAD

**Issue by phsantiago** [ErickWendel/downloading-files-from-s3-streams-and-promises#1]
@ErickWendel hello there! It's been so long, how's everything?
At first congratulations about the knowledge that you're sharing man. Thats precious.

So, I found a good way to set an example of abstraction here:
https://github.com/ErickWendel/downloading-files-from-s3-streams-and-promises/blob/master/examples/streams-example.js#L37

We can abstract S3 into a `fileStorage` function or class or plain object. It's very helpful to turn the code more readable way, and also implement things like read from local when in development and read from S3 in staging/production.

It can reduce the friction of people run the repo in their own machine to see the code working in practice.

**Comment by ErickWendel** [comment]
Indeed! This example was built to help people with their best understanding. I agree it's not the best approach for production environments, on my serverless apps training web course, I've shown how to make it better. Thanks mate!
